id: I4C5436A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:47:13+00:00'
last_modified: '2022-06-08T12:44:40.177261+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18484
  title: ཐང་གི་སྙན་ངག་སུམ་བརྒྱ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    AEB5:
      image_group_id: I8LS18486
      title: Volume 1 of nad thog sman pa'i lag deb/
      total_pages: 601
      order: 1
      base_file: AEB5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
