id: opecha:P006941
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18484
  title: ཐང་གི་སྙན་ངག་སུམ་བརྒྱ་བ།
  volume:
    13cccc629813449f94b1d47d484316a2:
      image_group_id: I8LS18486
      title: Volume 1 of nad thog sman pa'i lag deb/
      volume_number: 1
      total_pages: 601
  author: ''
ebook_metadata:
  title: ཐང་གི་སྙན་ངག་སུམ་བརྒྱ་བ།
  author: ''
  sku: P006941
  cover: cover.jpg
  layers:
  - pagination
