id: P006941
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18484
  title: ཐང་གི་སྙན་ངག་སུམ་བརྒྱ་བ།
  author: ''
  volumes:
    13cccc629813449f94b1d47d484316a2:
      image_group_id: I8LS18486
      title: Volume 1 of nad thog sman pa'i lag deb/
      volume_number: 1
      total_pages: 601
      base_file: v001.txt
