id: P006941
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18484
  title: ཐང་གི་སྙན་ངག་སུམ་བརྒྱ་བ།
  author: ''
  volumes:
    321016cbab2443909aaee295926ab4c8:
      image_group_id: I8LS18486
      title: ''
      volume_number: 1
      total_pages: 601
ebook_metadata:
  title: ཐང་གི་སྙན་ངག་སུམ་བརྒྱ་བ།
  author: ''
  sku: P006941
  cover: cover.jpg
  layers:
  - pagination
